/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTERFACE_H_RPCGEN
#define _INTERFACE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data {
	char *nome;
	char *nivel;
	double sal_bruto;
	int n_dependentes;
};
typedef struct data data;

#define CALCULA_LIQUIDO 0x20000001
#define CALCULA_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define calcular_salario 1
extern  double * calcular_salario_1(data *, CLIENT *);
extern  double * calcular_salario_1_svc(data *, struct svc_req *);
extern int calcula_liquido_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define calcular_salario 1
extern  double * calcular_salario_1();
extern  double * calcular_salario_1_svc();
extern int calcula_liquido_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);

#else /* K&R C */
extern bool_t xdr_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTERFACE_H_RPCGEN */
