/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTERFACE_H_RPCGEN
#define _INTERFACE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data {
	int idade;
};
typedef struct data data;

#define CALCULA_CATEGORIA 0x20000001
#define CATEGORIA_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define CATEGORIA 1
extern  char * categoria_1(data *, CLIENT *);
extern  char * categoria_1_svc(data *, struct svc_req *);
extern int calcula_categoria_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CATEGORIA 1
extern  char * categoria_1();
extern  char * categoria_1_svc();
extern int calcula_categoria_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);

#else /* K&R C */
extern bool_t xdr_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTERFACE_H_RPCGEN */
